import mongoose from 'mongoose';

/**
 * CaseLaws model – stores structured metadata for Indian court cases.
 * Source: eCourts, public legal databases.
 * IMPORTANT: Only metadata and summaries are stored. Full judgments are NOT stored.
 */
const caseLawsSchema = new mongoose.Schema(
    {
        caseTitle: {
            type: String,
            required: true,
            trim: true,
        },
        court: {
            type: String,
            required: true,
            trim: true,
        },
        date: {
            type: Date,
        },
        judges: [{ type: String, trim: true }],
        keywords: [{ type: String, trim: true }],
        summary: {
            type: String,
            required: true,
            trim: true,
        },
        source: {
            type: String,
            default: 'eCourts',
            trim: true,
        },
        sourceLink: {
            type: String,
            trim: true,
            default: '',
        },
        lastUpdated: {
            type: Date,
            default: Date.now,
        },
        // TF-IDF embedding vector for semantic search (generated by embeddingService)
        embedding: {
            type: [Number],
            default: [],
            select: false, // not returned by default queries — fetched explicitly by vectorStore
        },
    },
    { timestamps: true }
);

// Compound text index for full-text search
caseLawsSchema.index(
    { caseTitle: 'text', summary: 'text', keywords: 'text', court: 'text' },
    {
        name: 'case_laws_text',
        weights: { caseTitle: 10, keywords: 6, court: 4, summary: 3 },
        default_language: 'english',
    }
);

// Unique case title + court to prevent duplicate entries
caseLawsSchema.index(
    { caseTitle: 1, court: 1 },
    { unique: true, name: 'case_laws_title_court_unique', sparse: true }
);
caseLawsSchema.index({ lastUpdated: -1 }, { name: 'case_laws_last_updated' });
caseLawsSchema.index({ date: -1 }, { name: 'case_laws_date_desc' });
// Sparse index for semantic search
caseLawsSchema.index({ embedding: 1 }, { name: 'case_laws_embedding', sparse: true });

export default mongoose.model('CaseLaws', caseLawsSchema);
