import mongoose from 'mongoose';

/**
 * LegalActs model – stores structured metadata for Indian statutory acts/sections.
 * Source: IndiaCode (https://www.indiacode.nic.in) and similar public sources.
 * Full judgments and raw HTML are NOT stored — only metadata/summaries.
 */
const legalActsSchema = new mongoose.Schema(
    {
        title: {
            type: String,
            required: true,
            trim: true,
        },
        actName: {
            type: String,
            required: true,
            trim: true,
        },
        section: {
            type: String,
            trim: true,
            default: '',
        },
        description: {
            type: String,
            required: true,
            trim: true,
        },
        keywords: [{ type: String, trim: true }],
        source: {
            type: String,
            default: 'IndiaCode',
            trim: true,
        },
        sourceLink: {
            type: String,
            trim: true,
            default: '',
        },
        lastUpdated: {
            type: Date,
            default: Date.now,
        },
        // TF-IDF embedding vector for semantic search (generated by embeddingService)
        embedding: {
            type: [Number],
            default: [],
            select: false, // not returned by default queries — fetched explicitly by vectorStore
        },
    },
    { timestamps: true }
);

// Compound text index for full-text search across key fields
legalActsSchema.index(
    { title: 'text', actName: 'text', section: 'text', description: 'text', keywords: 'text' },
    {
        name: 'legal_acts_text',
        weights: { title: 10, actName: 8, section: 6, keywords: 5, description: 3 },
        default_language: 'english',
    }
);

// Unique constraint to prevent duplicate section entries per act
legalActsSchema.index({ actName: 1, section: 1 }, { unique: true, name: 'legal_acts_act_section_unique', sparse: true });
legalActsSchema.index({ lastUpdated: -1 }, { name: 'legal_acts_last_updated' });
// Sparse index for semantic search — only indexes docs that have embeddings
legalActsSchema.index({ embedding: 1 }, { name: 'legal_acts_embedding', sparse: true });

export default mongoose.model('LegalActs', legalActsSchema);
