/**
 * Static legal dataset embedded in the frontend.
 * This ensures the Legal Research page works IMMEDIATELY without any backend call.
 * API search enriches/extends these results — it is never the sole source of truth.
 */

import type { LegalResult } from './legalApi';

// ─── Acts & Sections ──────────────────────────────────────────────────────────
export const STATIC_ACTS: LegalResult[] = [
    // ── Indian Penal Code ──
    { type: 'act', id: 's-ipc-299', title: 'Culpable Homicide', subtitle: 'Indian Penal Code, 1860 — Section 299', description: 'Whoever causes death by doing an act with the intention of causing death, or with the intention of causing such bodily injury as is likely to cause death, or with the knowledge that he is likely by such act to cause death, commits the offence of culpable homicide.', keywords: ['culpable homicide', 'death', 'IPC 299', 'ipc 299'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-300', title: 'Murder', subtitle: 'Indian Penal Code, 1860 — Section 300', description: 'Culpable homicide is murder if the act by which the death is caused is done with the intention of causing death, or it is done with the intention of causing such bodily injury as the offender knows to be likely to cause death.', keywords: ['murder', 'death', 'IPC 300', 'ipc 300', 'killing'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-302', title: 'Punishment for Murder', subtitle: 'Indian Penal Code, 1860 — Section 302', description: 'Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine.', keywords: ['murder', 'death', 'life imprisonment', 'IPC 302', 'ipc 302', 'killing', 'punishment murder'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-304', title: 'Culpable Homicide Not Amounting to Murder', subtitle: 'Indian Penal Code, 1860 — Section 304', description: 'Whoever commits culpable homicide not amounting to murder shall be punished with imprisonment for life, or imprisonment of either description for a term which may extend to 10 years, and shall also be liable to fine.', keywords: ['culpable homicide', 'IPC 304', 'ipc 304', 'manslaughter', 'death'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-307', title: 'Attempt to Murder', subtitle: 'Indian Penal Code, 1860 — Section 307', description: 'Whoever does any act with such intention or knowledge, and under such circumstances that, if he by that act caused death, he would be guilty of murder, shall be punished.', keywords: ['attempt to murder', 'IPC 307', 'ipc 307', 'shooting', 'grievous hurt'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-319', title: 'Hurt', subtitle: 'Indian Penal Code, 1860 — Section 319', description: 'Whoever causes bodily pain, disease or infirmity to any person is said to cause hurt.', keywords: ['hurt', 'bodily harm', 'IPC 319', 'ipc 319'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-320', title: 'Grievous Hurt', subtitle: 'Indian Penal Code, 1860 — Section 320', description: 'Emasculation, permanent privation of sight, permanent disfiguration of the head or face, fracture or dislocation of a bone or tooth, or any hurt which endangers life are designated as "grievous".', keywords: ['grievous hurt', 'IPC 320', 'ipc 320', 'injury', 'serious hurt'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-354', title: 'Assault or Criminal Force with Intent to Outrage Modesty', subtitle: 'Indian Penal Code, 1860 — Section 354', description: 'Whoever assaults or uses criminal force to any woman, intending to outrage or knowing it to be likely that he will thereby outrage her modesty, shall be punished with imprisonment of either description for a term extending to two years.', keywords: ['outraging modesty', 'assault woman', 'IPC 354', 'ipc 354', 'molestation'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-375', title: 'Rape', subtitle: 'Indian Penal Code, 1860 — Section 375', description: 'A man is said to commit "rape" if he penetrates his penis, to any extent, into the vagina, mouth, urethra or anus of a woman or makes her do so with him or any other person without consent, or if the woman is under 18 years of age.', keywords: ['rape', 'sexual assault', 'consent', 'IPC 375', 'ipc 375'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-376', title: 'Punishment for Rape', subtitle: 'Indian Penal Code, 1860 — Section 376', description: 'Whoever commits rape shall be punished with rigorous imprisonment of either description for a term which shall not be less than 10 years, but which may extend to imprisonment for life.', keywords: ['rape', 'punishment', 'sexual offence', 'IPC 376', 'ipc 376'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-378', title: 'Theft', subtitle: 'Indian Penal Code, 1860 — Section 378', description: 'Whoever, intending to take dishonestly any moveable property out of the possession of any person without that person\'s consent, moves that property in order to such taking, is said to commit theft.', keywords: ['theft', 'stealing', 'property', 'IPC 378', 'ipc 378'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-379', title: 'Punishment for Theft', subtitle: 'Indian Penal Code, 1860 — Section 379', description: 'Whoever commits theft shall be punished with imprisonment of either description for a term which may extend to 3 years, or with fine, or with both.', keywords: ['theft', 'stealing', 'property', 'IPC 379', 'ipc 379'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-390', title: 'Robbery', subtitle: 'Indian Penal Code, 1860 — Section 390', description: 'In all robbery there is either theft or extortion. Theft is "robbery" if, in order to commit theft or in committing or in carrying away property obtained by theft, the offender voluntarily causes or attempts to cause death or hurt.', keywords: ['robbery', 'theft', 'force', 'IPC 390', 'ipc 390'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-391', title: 'Dacoity', subtitle: 'Indian Penal Code, 1860 — Section 391', description: 'When five or more persons conjointly commit or attempt to commit a robbery, or where the whole number of persons conjointly committing or attempting to commit a robbery, and persons present and aiding such commission or attempt, amount to five or more, every person so committing is said to commit dacoity.', keywords: ['dacoity', 'robbery', 'gang', 'IPC 391', 'ipc 391'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-406', title: 'Punishment for Criminal Breach of Trust', subtitle: 'Indian Penal Code, 1860 — Section 406', description: 'Whoever commits criminal breach of trust shall be punished with imprisonment of either description for a term which may extend to 3 years, or with fine, or with both.', keywords: ['breach of trust', 'cheating', 'property', 'IPC 406', 'ipc 406'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-420', title: 'Cheating and Dishonestly Inducing Delivery of Property', subtitle: 'Indian Penal Code, 1860 — Section 420', description: 'Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, or anything which is signed or sealed, shall be punished with imprisonment of either description for a term extending to 7 years.', keywords: ['cheating', 'fraud', 'property', 'dishonestly', 'IPC 420', 'ipc 420'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-463', title: 'Forgery', subtitle: 'Indian Penal Code, 1860 — Section 463', description: 'Whoever makes any false document or electronic record or part of a document or electronic record with intent to cause damage or injury to the public or to any person, commits forgery.', keywords: ['forgery', 'false document', 'IPC 463', 'ipc 463', 'fake document'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-498a', title: 'Cruelty by Husband or Relatives', subtitle: 'Indian Penal Code, 1860 — Section 498A', description: 'Whoever, being the husband or the relative of the husband of a woman, subjects such woman to cruelty shall be punished with imprisonment for a term extending to 3 years and shall also be liable to fine.', keywords: ['cruelty', 'domestic violence', 'husband', 'dowry harassment', 'IPC 498A', 'ipc 498a', 'IPC 498-A'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ipc-304b', title: 'Dowry Death', subtitle: 'Indian Penal Code, 1860 — Section 304B', description: 'Where the death of a woman is caused by any burns or bodily injury or occurs under suspicious circumstances within 7 years of marriage and it is shown that she was subjected to cruelty or harassment by her husband or his relatives in connection with demand for dowry, such death shall be called "dowry death".', keywords: ['dowry death', 'domestic violence', 'IPC 304B', 'ipc 304b', 'cruelty'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },

    // ── CrPC ──
    { type: 'act', id: 's-crpc-154', title: 'First Information Report (FIR)', subtitle: 'Code of Criminal Procedure, 1973 — Section 154', description: 'Every information relating to the commission of a cognizable offence, if given orally to an officer in charge of a police station, shall be reduced to writing by him or under his direction, and be read over to the informant; and every such information, whether given in writing or reduced to writing as aforesaid, shall be signed by the person giving it.', keywords: ['FIR', 'first information report', 'cognizable', 'police', 'CrPC 154', 'crpc 154'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-crpc-161', title: 'Examination of Witnesses by Police', subtitle: 'Code of Criminal Procedure, 1973 — Section 161', description: 'Any police officer making an investigation may examine orally any person supposed to be acquainted with the facts and circumstances of the case.', keywords: ['witness', 'examination', 'police', 'investigation', 'CrPC 161', 'crpc 161'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-crpc-164', title: 'Recording of Confessions and Statements', subtitle: 'Code of Criminal Procedure, 1973 — Section 164', description: 'Any Metropolitan Magistrate or Judicial Magistrate may record any confession or statement made to him in the course of an investigation under this Chapter.', keywords: ['confession', 'statement', 'magistrate', 'investigation', 'CrPC 164', 'crpc 164'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-crpc-173', title: 'Report of Police Officer on Completion of Investigation (Chargesheet)', subtitle: 'Code of Criminal Procedure, 1973 — Section 173', description: 'Every investigation under this Chapter shall be completed without unnecessary delay. As soon as it is completed, the officer in charge of the police station shall forward a report (chargesheet) to a Magistrate.', keywords: ['chargesheet', 'police report', 'investigation', 'CrPC 173', 'crpc 173'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-crpc-437', title: 'Bail in Non-Bailable Offence', subtitle: 'Code of Criminal Procedure, 1973 — Section 437', description: 'When any person accused of, or suspected of, the commission of any non-bailable offence is arrested or detained without warrant by an officer in charge of a police station, or appears or is brought before a Court, he may be released on bail.', keywords: ['bail', 'non-bailable', 'arrest', 'CrPC 437', 'crpc 437'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-crpc-438', title: 'Anticipatory Bail', subtitle: 'Code of Criminal Procedure, 1973 — Section 438', description: 'When any person has reason to believe that he may be arrested on accusation of having committed a non-bailable offence, he may apply to the High Court or the Court of Session for a direction that in the event of such arrest he shall be released on bail.', keywords: ['anticipatory bail', 'arrest', 'high court', 'CrPC 438', 'crpc 438', 'pre-arrest bail'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-crpc-439', title: 'Special Powers of High Court or Court of Session Regarding Bail', subtitle: 'Code of Criminal Procedure, 1973 — Section 439', description: 'A High Court or Court of Session may direct that any person accused of an offence and in custody be released on bail and may impose any condition which it considers necessary.', keywords: ['bail', 'high court', 'session court', 'CrPC 439', 'crpc 439'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },

    // ── Indian Contract Act ──
    { type: 'act', id: 's-ica-10', title: 'What Agreements Are Contracts', subtitle: 'Indian Contract Act, 1872 — Section 10', description: 'All agreements are contracts if they are made by the free consent of parties competent to contract, for a lawful consideration and with a lawful object, and are not hereby expressly declared to be void.', keywords: ['contract', 'agreement', 'consent', 'competent', 'ICA 10', 'ica 10', 'valid contract'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ica-13', title: 'Consent', subtitle: 'Indian Contract Act, 1872 — Section 13', description: 'Two or more persons are said to consent when they agree upon the same thing in the same sense.', keywords: ['consent', 'agreement', 'meeting of minds', 'ICA 13', 'ica 13'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ica-14', title: 'Free Consent', subtitle: 'Indian Contract Act, 1872 — Section 14', description: 'Consent is said to be free when it is not caused by coercion, undue influence, fraud, misrepresentation, or mistake.', keywords: ['free consent', 'coercion', 'fraud', 'misrepresentation', 'ICA 14', 'ica 14'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ica-73', title: 'Compensation for Breach of Contract', subtitle: 'Indian Contract Act, 1872 — Section 73', description: 'When a contract has been broken, the party who suffers by such breach is entitled to receive, from the party who has broken it, compensation for any loss or damage caused to him thereby, which naturally arose in the usual course of things from such breach.', keywords: ['breach of contract', 'compensation', 'damages', 'ICA 73', 'ica 73'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-ica-74', title: 'Compensation for Breach Where Penalty Stipulated', subtitle: 'Indian Contract Act, 1872 — Section 74', description: 'When a contract has been broken, if a sum is named in the contract as the amount to be paid in case of such breach, or if the contract contains any other stipulation by way of penalty, the party complaining of the breach is entitled to receive from the party who has broken it reasonable compensation.', keywords: ['penalty', 'liquidated damages', 'breach', 'ICA 74', 'ica 74'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },

    // ── Constitution ──
    { type: 'act', id: 's-con-14', title: 'Equality Before Law', subtitle: 'Constitution of India, 1950 — Article 14', description: 'The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.', keywords: ['equality', 'equal protection', 'discrimination', 'Article 14', 'article 14', 'fundamental right'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in/handle/123456789/1104' },
    { type: 'act', id: 's-con-19', title: 'Freedom of Speech and Expression', subtitle: 'Constitution of India, 1950 — Article 19', description: 'All citizens shall have the right to freedom of speech and expression; to assemble peaceably and without arms; to form associations or unions; to move freely throughout the territory of India; to reside and settle in any part of India; to practise any profession, or to carry on any occupation, trade or business.', keywords: ['freedom of speech', 'fundamental rights', 'expression', 'Article 19', 'article 19', 'free speech'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in/handle/123456789/1104' },
    { type: 'act', id: 's-con-21', title: 'Protection of Life and Personal Liberty', subtitle: 'Constitution of India, 1950 — Article 21', description: 'No person shall be deprived of his life or personal liberty except according to procedure established by law.', keywords: ['fundamental right', 'life', 'liberty', 'Article 21', 'article 21', 'constitutional right', 'right to life'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in/handle/123456789/1104' },
    { type: 'act', id: 's-con-32', title: 'Right to Constitutional Remedies (Writs)', subtitle: 'Constitution of India, 1950 — Article 32', description: 'The right to move the Supreme Court by appropriate proceedings for enforcement of fundamental rights is hereby guaranteed. The Supreme Court shall have the power to issue directions or orders or writs, including writs in the nature of habeas corpus, mandamus, prohibition, quo warranto and certiorari.', keywords: ['writ', 'habeas corpus', 'mandamus', 'Article 32', 'article 32', 'fundamental rights enforcement', 'supreme court'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in/handle/123456789/1104' },

    // ── POCSO ──
    { type: 'act', id: 's-pocso-4', title: 'Punishment for Penetrative Sexual Assault', subtitle: 'Protection of Children from Sexual Offences Act, 2012 — Section 4', description: 'Whoever commits penetrative sexual assault shall be punished with rigorous imprisonment for a term which shall not be less than 10 years but extending to imprisonment for life, and shall also be liable to fine.', keywords: ['POCSO', 'child abuse', 'sexual assault', 'minor', 'POCSO 4', 'pocso', 'child protection'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-pocso-7', title: 'Sexual Assault on Child', subtitle: 'Protection of Children from Sexual Offences Act, 2012 — Section 7', description: 'Whoever, with sexual intent touches the vagina, penis, anus or breast of the child or makes the child touch the vagina, penis, anus or breast of such person or any other person, commits sexual assault.', keywords: ['POCSO', 'child sexual assault', 'minor', 'POCSO 7', 'pocso', 'child abuse'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },

    // ── IT Act ──
    { type: 'act', id: 's-it-66', title: 'Computer Related Offences', subtitle: 'Information Technology Act, 2000 — Section 66', description: 'If any person, dishonestly or fraudulently, does any act referred to in section 43, he shall be punishable with imprisonment for a term which may extend to 3 years or with fine which may extend to five lakh rupees.', keywords: ['cyber crime', 'hacking', 'computer', 'IT Act 66', 'it act 66', 'digital offence'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
    { type: 'act', id: 's-it-67', title: 'Publishing Obscene Material in Electronic Form', subtitle: 'Information Technology Act, 2000 — Section 67', description: 'Whoever publishes or transmits or causes to be published in the electronic form, any material which is lascivious or appeals to the prurient interest shall be punished with imprisonment extending to 3 years and fine extending to five lakh rupees.', keywords: ['obscene', 'pornography', 'internet', 'IT Act 67', 'it act 67', 'cyber crime'], source: 'IndiaCode', sourceLink: 'https://www.indiacode.nic.in' },
];

// ─── Case Laws ────────────────────────────────────────────────────────────────
export const STATIC_CASES: LegalResult[] = [
    { type: 'case', id: 's-case-kesav', title: 'Kesavananda Bharati v. State of Kerala', subtitle: 'Supreme Court of India', description: 'Landmark 13-judge bench ruling establishing the "basic structure" doctrine — Parliament cannot amend the Constitution so as to destroy its basic structure, such as supremacy of the Constitution, rule of law, judicial review, and separation of powers. (AIR 1973 SC 1461)', keywords: ['constitution', 'basic structure', 'fundamental rights', 'amendment', 'kesavananda', 'parliament'], source: 'Supreme Court of India', sourceLink: 'https://main.sci.gov.in' },
    { type: 'case', id: 's-case-maneka', title: 'Maneka Gandhi v. Union of India', subtitle: 'Supreme Court of India', description: 'Expanded scope of Article 21 — the right to life and personal liberty is not merely a procedural right. The "procedure established by law" must be fair, just, and reasonable. Passports cannot be impounded without giving an opportunity to be heard. (AIR 1978 SC 597)', keywords: ['Article 21', 'personal liberty', 'passport', 'natural justice', 'maneka', 'due process'], source: 'Supreme Court of India', sourceLink: 'https://main.sci.gov.in' },
    { type: 'case', id: 's-case-vishaka', title: 'Vishaka v. State of Rajasthan', subtitle: 'Supreme Court of India', description: 'Landmark judgment laying down the Vishaka Guidelines for prevention of sexual harassment of women at the workplace. Later codified as the POSH Act, 2013. Every employer is obligated to provide a safe working environment. (AIR 1997 SC 3011)', keywords: ['sexual harassment', 'workplace', 'women rights', 'guidelines', 'POSH', 'vishaka'], source: 'Supreme Court of India', sourceLink: 'https://main.sci.gov.in' },
    { type: 'case', id: 's-case-shreya', title: 'Shreya Singhal v. Union of India', subtitle: 'Supreme Court of India', description: 'Struck down Section 66A of the IT Act as unconstitutional — it violated the right to freedom of speech and expression under Article 19(1)(a) of the Constitution. The provision criminalising online speech was vague and overbroad. (AIR 2015 SC 1523)', keywords: ['Section 66A', 'IT Act', 'freedom of speech', 'internet', 'shreya singhal', 'unconstitutional', 'social media'], source: 'Supreme Court of India', sourceLink: 'https://main.sci.gov.in' },
    { type: 'case', id: 's-case-privacy', title: 'Justice K.S. Puttaswamy v. Union of India', subtitle: 'Supreme Court of India', description: '9-judge bench unanimously held that the right to privacy is a fundamental right protected under Article 21 of the Constitution. Privacy forms an intrinsic part of the right to life and personal liberty. This also impacted the Aadhaar case. (AIR 2017 SC 4161)', keywords: ['right to privacy', 'fundamental right', 'Aadhaar', 'Article 21', 'data protection', 'puttaswamy', 'privacy'], source: 'Supreme Court of India', sourceLink: 'https://main.sci.gov.in' },
    { type: 'case', id: 's-case-navtej', title: 'Navtej Singh Johar v. Union of India', subtitle: 'Supreme Court of India', description: 'Decriminalised consensual same-sex relations between adults by reading down Section 377 IPC. Held that Section 377 to the extent it criminalised consensual sex between adults of the same gender violates Articles 14, 15, 19, and 21 of the Constitution. (AIR 2018 SC 4321)', keywords: ['Section 377', 'homosexuality', 'LGBT rights', 'decriminalisation', 'fundamental rights', 'navtej'], source: 'Supreme Court of India', sourceLink: 'https://main.sci.gov.in' },
    { type: 'case', id: 's-case-dkbasu', title: 'D.K. Basu v. State of West Bengal', subtitle: 'Supreme Court of India', description: 'Issued comprehensive guidelines to be mandatorily followed in all cases of arrest and detention to prevent custodial deaths and torture. Held that custodial violence infringes Article 21. These guidelines were later incorporated into the CrPC amendments. (AIR 1997 SC 610)', keywords: ['custodial death', 'arrest', 'police', 'human rights', 'detention', 'DK Basu', 'custody', 'torture'], source: 'Supreme Court of India', sourceLink: 'https://main.sci.gov.in' },
    { type: 'case', id: 's-case-shahbano', title: 'Mohd. Ahmed Khan v. Shah Bano Begum', subtitle: 'Supreme Court of India', description: 'Held that a Muslim divorced woman is entitled to claim maintenance under Section 125 CrPC (secular law), overriding personal law. Sparked nationwide debate on uniform civil code. The judgment led to the Muslim Women (Protection of Rights on Divorce) Act 1986. (AIR 1985 SC 945)', keywords: ['Muslim personal law', 'maintenance', 'Section 125 CrPC', 'divorce', 'Shah Bano', 'uniform civil code', 'alimony'], source: 'Supreme Court of India', sourceLink: 'https://main.sci.gov.in' },
    { type: 'case', id: 's-case-aruna', title: 'Aruna Shanbaug v. Union of India', subtitle: 'Supreme Court of India', description: 'Permitted passive euthanasia under strict guidelines in India. Held that passive euthanasia (withdrawal of life support) can be allowed with the permission of the High Court. Active euthanasia remains illegal. (AIR 2011 SC 1290)', keywords: ['euthanasia', 'passive euthanasia', 'right to die', 'living will', 'Article 21', 'aruna shanbaug'], source: 'Supreme Court of India', sourceLink: 'https://main.sci.gov.in' },
    { type: 'case', id: 's-case-indira', title: 'Indira Gandhi v. Raj Narain', subtitle: 'Supreme Court of India', description: 'Held that free and fair elections are part of the basic structure of the Constitution. The Parliament\'s attempt to validate the election by a constitutional amendment was struck down. This case directly contributed to the proclamation of the Emergency in 1975. (AIR 1975 SC 2299)', keywords: ['election law', 'basic structure', 'democracy', 'emergency', 'indira gandhi'], source: 'Supreme Court of India', sourceLink: 'https://main.sci.gov.in' },
    { type: 'case', id: 's-case-mc-mehta', title: 'M.C. Mehta v. Union of India (Taj Trapezium)', subtitle: 'Supreme Court of India', description: 'Established the "absolute liability" principle for hazardous industries — an enterprise engaged in a hazardous activity is absolutely liable to compensate those who are harmed, with no exceptions. Foundational environmental law case in India. (AIR 1987 SC 1086)', keywords: ['environment', 'absolute liability', 'hazardous industry', 'MC Mehta', 'pollution', 'Taj Mahal'], source: 'Supreme Court of India', sourceLink: 'https://main.sci.gov.in' },
    { type: 'case', id: 's-case-olga-tellis', title: 'Olga Tellis v. Bombay Municipal Corporation', subtitle: 'Supreme Court of India', description: 'Held that the right to livelihood is part of the right to life under Article 21. Pavement dwellers cannot be evicted without being given an opportunity to be heard. The right to life includes the right to earn a livelihood. (AIR 1986 SC 180)', keywords: ['right to livelihood', 'Article 21', 'right to life', 'eviction', 'pavement dwellers', 'olga tellis'], source: 'Supreme Court of India', sourceLink: 'https://main.sci.gov.in' },
];

// ─── Smart search function ────────────────────────────────────────────────────

/**
 * Handles "IPC 302" style queries — splits prefix/number
 */
function normalizeQuery(q: string): string[] {
    const terms = [q.toLowerCase().trim()];

    // "IPC 302" → also try "302" and "ipc"
    const ipcMatch = q.match(/^(ipc|crpc|ica|it act|pocso|article)\s*(\d+\w*)/i);
    if (ipcMatch) {
        terms.push(ipcMatch[2].toLowerCase()); // just the number
        terms.push(ipcMatch[1].toLowerCase()); // just the act prefix
        terms.push(`${ipcMatch[1]} ${ipcMatch[2]}`.toLowerCase()); // normalised
    }

    // "302" alone → also try "IPC 302"
    const numOnly = q.match(/^(\d+\w*)$/);
    if (numOnly) {
        terms.push(`ipc ${q.toLowerCase()}`);
        terms.push(`crpc ${q.toLowerCase()}`);
        terms.push(`section ${q.toLowerCase()}`);
    }

    return [...new Set(terms)];
}

function itemMatchesTerms(item: LegalResult, terms: string[]): boolean {
    const searchable = [
        item.title,
        item.subtitle || '',
        item.description,
        ...(item.keywords || []),
    ].map(s => s.toLowerCase()).join(' ');

    return terms.some(t => searchable.includes(t));
}

/**
 * Search the static dataset. Returns { acts, cases, sections }.
 */
export function searchStaticData(query: string): { acts: LegalResult[]; cases: LegalResult[]; sections: LegalResult[] } {
    if (!query.trim()) {
        return { acts: [], cases: [], sections: [] };
    }

    const terms = normalizeQuery(query);

    const acts = STATIC_ACTS.filter(item => itemMatchesTerms(item, terms));
    const cases = STATIC_CASES.filter(item => itemMatchesTerms(item, terms));

    return { acts, cases, sections: [] };
}

/**
 * Popular sections to show on the home/default view.
 */
export const POPULAR_ACTS: LegalResult[] = [
    STATIC_ACTS.find(a => a.id === 's-ipc-302')!,
    STATIC_ACTS.find(a => a.id === 's-ipc-420')!,
    STATIC_ACTS.find(a => a.id === 's-crpc-154')!,
    STATIC_ACTS.find(a => a.id === 's-crpc-438')!,
    STATIC_ACTS.find(a => a.id === 's-con-21')!,
    STATIC_ACTS.find(a => a.id === 's-ipc-498a')!,
].filter(Boolean);
