import mongoose from 'mongoose';

const messageSchema = new mongoose.Schema(
  {
    conversationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Conversation',
      required: true,
      index: true,
    },
    senderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    // ── Encrypted content (AES-256-GCM) ──────────────────────────────────────
    // NEVER store plaintext. Always store ciphertext + IV + authTag.
    encryptedContent: { type: String, default: null },  // base64 ciphertext
    iv: { type: String, default: null },                 // base64 12-byte nonce
    authTag: { type: String, default: null },            // base64 16-byte GCM tag
    keyVersion: { type: String, default: '1', index: true },

    // ── Message type ──────────────────────────────────────────────────────────
    messageType: {
      type: String,
      enum: ['text', 'image', 'voice', 'file', 'video', 'system', 'forwarded'],
      default: 'text',
    },

    // ── Delivery state ────────────────────────────────────────────────────────
    deliveryStatus: {
      type: String,
      enum: ['sent', 'delivered', 'read'],
      default: 'sent',
    },

    // ── Threading ─────────────────────────────────────────────────────────────
    replyTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'CommunityMessage',
      default: null,
    },

    // Forward source
    forwardedFrom: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'CommunityMessage',
      default: null,
    },

    // ── Read tracking (stored here for efficiency on small conversations) ─────
    // For large channels, use the ConversationParticipant.lastReadMessageId approach
    readBy: [
      {
        userId:   { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
        readAt:   { type: Date },
      },
    ],

    // ── Reactions (denormalized count summary for fast display) ───────────────
    reactionsSummary: [
      {
        emoji:    { type: String },
        count:    { type: Number, default: 0 },
        userIds:  [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
      },
    ],

    // ── Moderation state ──────────────────────────────────────────────────────
    isEdited: { type: Boolean, default: false },
    editedAt: { type: Date, default: null },
    editHistory: [
      {
        encryptedContent: String,
        iv: String,
        authTag: String,
        editedAt: Date,
      },
    ],

    isDeleted:   { type: Boolean, default: false, index: true },
    deletedAt:   { type: Date, default: null },
    deletedBy:   { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },

    isPinned:  { type: Boolean, default: false },
    isStarred: { type: Boolean, default: false },

    // Admin moderation
    isFlagged:    { type: Boolean, default: false },
    flagReason:   { type: String, default: null },   // legacy free-text (deprecated)
    flagCategory: { type: String, default: null },   // structured enum from CommunityReport
    isModerated:  { type: Boolean, default: false },
    moderatedBy:  { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },

    // ── Idempotency / Replay protection ──────────────────────────────────────
    // clientMessageId: UUID generated by sender client — prevents duplicates on retry
    clientMessageId: { type: String, index: true, sparse: true },
    // nonce: server-generated random value stored alongside message for anti-replay
    nonce: { type: String, default: null },

    // ── Attachments (IDs to MessageAttachment docs) ───────────────────────────
    attachments: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'MessageAttachment',
      },
    ],

    // ── System message payload (for type === 'system') ────────────────────────
    systemPayload: {
      event: { type: String }, // 'member_joined', 'member_left', 'channel_created', etc.
      data:  { type: Map, of: String },
    },
  },
  { timestamps: true }
);

// Performance indexes
messageSchema.index({ conversationId: 1, createdAt: -1 });           // message list
messageSchema.index({ conversationId: 1, isDeleted: 1, createdAt: -1 }); // filtered list
messageSchema.index({ senderId: 1, createdAt: -1 });
messageSchema.index({ clientMessageId: 1 }, { unique: true, sparse: true }); // dedup

export default mongoose.model('CommunityMessage', messageSchema);
